CREATE PROCEDURE [dbo].[spCreateExternalUniqueID] @InputUniqueID UNIQUEIDENTIFIER = NULL,
@OutputUniqueID UNIQUEIDENTIFIER OUTPUT AS BEGIN
SET
    NOCOUNT ON DECLARE @ExternalUniqueID UNIQUEIDENTIFIER = @InputUniqueID;

IF @ExternalUniqueID IS NULL
AND CONTEXT_INFO() IS NULL BEGIN
SET
    @ExternalUniqueID = NEWID()
END IF @ExternalUniqueID IS NOT NULL BEGIN
SET
    CONTEXT_INFO @ExternalUniqueID
END
ELSE IF CONTEXT_INFO() IS NOT NULL BEGIN
SET
    @ExternalUniqueID = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER)
END
SET
    @OutputUniqueID = @ExternalUniqueID
END